### health check
GET {{host}}/health

### create a card and store in database
POST {{host}}/card
Content-Type: application/json

{
  "name": "test-card",
  "issuerBank": "test-bank",
  "milesPerDollar": 0,
  "network": "test-network"
}

### get all cards
GET {{host}}/cards/

### search for a card
GET {{host}}/card/{{$random.integer(0,10)}}

### delete card
DELETE {{host}}/card/2